remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


---
layout: page
title: Project 3
description: Description of Project 3.
nav_exclude: true
---
